import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div >
     <Image src={'/home.png'} alt='products' height={0} width={10000}/>
    </div>
 
    </div>
    
  )
}
